### ISSUE TITLE
Sync between web app and obsidian seems not to work.

### ISSUE THREAD

**Issue by nengelmann** [jonashaefele/audiopen-obsidian#2]
Dear Jonas,
thanks for this awesome idea and repo, much appreciated!

I have set up the plugin and the AudioPen settings according to the documentation in the readme, but have trouble with the sync of the web app and Obsidian. Here is a video, which shows what happens. 

https://github.com/jonashaefele/audiopen-obsidian/assets/120744129/bb9d9cb5-b2b6-40d3-af34-f83bb96a79c3

Am I doing anything wrong?

Thanks again for your time and work,
Nico

**Comment by nengelmann** [comment]
Okay, I now know what has caused this. On Linux, it seems like the **`Destination folder`** is **not allowed to be empty**.

So, **within** the **plugin settings**, **specify** any folder of vault as **`Destination folder`**. If you want to save it in the root directory, use `/`.

**Comment by jonashaefele** [comment]
Thanks for the nice words @nengelmann and sorry, somehow I didn't get pinged about this issue. I just found it.

Yes, as you noticed, if you don't add a folder, it'll default to `+ Inbox/AudioPen` and you have to overwrite that with the folder you want. In your case that's `/`

I'll look at changing the default to `/` because that should work for every vault.
